name: cliche
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - click>=8.0.0
  - psutil>=5.9.0
  - requests>=2.31.0
  - black>=23.0.0
  - pytest>=7.0.0
  - beautifulsoup4>=4.12.0
  - duckduckgo-search>=2.8.6
  - rich>=13.0.0
  - pip:
    - openai>=1.0.0
    - anthropic>=0.7.0
    - google-generativeai>=0.3.0
    - py3nvml>=0.2.7
    - pytest-asyncio>=0.21.0
    - crawl4ai>=0.4.3
    - html2text>=2024.2.26
    - mdformat>=0.7.0
    - art>=6.0
    - pydantic>=2.0.0
    - python-dotenv>=1.0.0
    - asyncio>=3.4.3
    - python-unsplash>=1.1.0
